- hosts: all
  become: yes
  tasks:
   - name: stop container
     shell: docker container stop webapp10
   - name: remove docker container
     shell: docker container rm webapp10
   - name: remove docker image
     shell: docker image rm -f prabha442/project-2
   - name: create new container
     shell: docker container run -itd --name webapp10 -p 9001:80 prabha442/project-2
